FROM rust:1-alpine as build

RUN rustup target add x86_64-unknown-linux-musl && \
    mkdir /app

WORKDIR /app
COPY . /app

RUN cargo build --release && strip target/release/init

FROM alpine:3.20.2

COPY --from=build /app/target/release/init /init

ENTRYPOINT [ "/init" ]
CMD [ "/bin/sh", "-c", "while true; do echo ping; sleep 1; done" ]
